name: real_estate_app
description: A comprehensive real estate app for landlords and tenants

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^14.0.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.8.0
  image_picker: ^1.0.2
  google_maps_flutter: ^2.2.3
  geolocator: ^10.0.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
